[2025-04-20T22:30:55.131+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T22:30:55.143+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:30:37.878916+00:00 [queued]>
[2025-04-20T22:30:55.148+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:30:37.878916+00:00 [queued]>
[2025-04-20T22:30:55.149+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-20T22:30:55.157+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-20 22:30:37.878916+00:00
[2025-04-20T22:30:55.162+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'manual__2025-04-20T22:30:37.878916+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpw4w5qudp']
[2025-04-20T22:30:55.163+0000] {standard_task_runner.py:105} INFO - Job 200: Subtask meteo_operations.save_meteo_data
[2025-04-20T22:30:55.165+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1162) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-20T22:30:55.165+0000] {standard_task_runner.py:72} INFO - Started process 1184 to run task
[2025-04-20T22:30:55.191+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:30:37.878916+00:00 [running]> on host 8e2c8626a9ef
[2025-04-20T22:30:55.240+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T22:30:37.878916+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T22:30:37.878916+00:00'
[2025-04-20T22:30:55.242+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T22:30:55.261+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-20T22:30:55.274+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T22:30:55.275+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=manual__2025-04-20T22:30:37.878916+00:00, execution_date=20250420T223037, start_date=20250420T223055, end_date=20250420T223055
[2025-04-20T22:30:55.298+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-20T22:30:55.314+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-20T22:30:55.316+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
