[2025-04-22T16:37:45.588+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T16:37:45.601+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.collect_meteo_data scheduled__2025-04-20T22:00:00+00:00 [queued]>
[2025-04-22T16:37:45.607+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.collect_meteo_data scheduled__2025-04-20T22:00:00+00:00 [queued]>
[2025-04-22T16:37:45.608+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-22T16:37:45.615+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.collect_meteo_data> on 2025-04-20 22:00:00+00:00
[2025-04-22T16:37:45.620+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.collect_meteo_data', 'scheduled__2025-04-20T22:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp6bv_i30b']
[2025-04-22T16:37:45.621+0000] {standard_task_runner.py:105} INFO - Job 213: Subtask meteo_operations.collect_meteo_data
[2025-04-22T16:37:45.623+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=42) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-22T16:37:45.623+0000] {standard_task_runner.py:72} INFO - Started process 64 to run task
[2025-04-22T16:37:45.651+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.collect_meteo_data scheduled__2025-04-20T22:00:00+00:00 [running]> on host 8e2c8626a9ef
[2025-04-22T16:37:45.707+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.collect_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-20T22:00:00+00:00'
[2025-04-22T16:37:45.707+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T16:37:46.383+0000] {python.py:240} INFO - Done. Returned value was: {'latitude': 21.4901, 'longitude': 39.1862, 'timestamp': '2025-04-22 00:00:00', 'temperature': 27.073501586914062, 'humidity': 77.0, 'wind_speed': 3.096837043762207, 'pm2_5': 108.30000305175781, 'co': 441.0}
[2025-04-22T16:37:46.405+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T16:37:46.406+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.collect_meteo_data, run_id=scheduled__2025-04-20T22:00:00+00:00, execution_date=20250420T220000, start_date=20250422T163745, end_date=20250422T163746
[2025-04-22T16:37:46.438+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-22T16:37:46.453+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-22T16:37:46.455+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
