[2025-04-20T22:21:37.453+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T22:21:37.467+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:18:50.765577+00:00 [queued]>
[2025-04-20T22:21:37.473+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:18:50.765577+00:00 [queued]>
[2025-04-20T22:21:37.474+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-20T22:21:37.484+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): meteo_operations.save_meteo_data> on 2025-04-20 22:18:50.765577+00:00
[2025-04-20T22:21:37.491+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'meteo_operations.save_meteo_data', 'manual__2025-04-20T22:18:50.765577+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp7ugb8ybp']
[2025-04-20T22:21:37.493+0000] {standard_task_runner.py:105} INFO - Job 167: Subtask meteo_operations.save_meteo_data
[2025-04-20T22:21:37.494+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=332) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-20T22:21:37.494+0000] {standard_task_runner.py:72} INFO - Started process 354 to run task
[2025-04-20T22:21:37.525+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.meteo_operations.save_meteo_data manual__2025-04-20T22:18:50.765577+00:00 [running]> on host 8e2c8626a9ef
[2025-04-20T22:21:37.585+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='meteo_operations.save_meteo_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T22:18:50.765577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T22:18:50.765577+00:00'
[2025-04-20T22:21:37.586+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T22:21:37.606+0000] {python.py:240} INFO - Done. Returned value was: Successfully inserted measurement into database
[2025-04-20T22:21:37.620+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T22:21:37.621+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=meteo_operations.save_meteo_data, run_id=manual__2025-04-20T22:18:50.765577+00:00, execution_date=20250420T221850, start_date=20250420T222137, end_date=20250420T222137
[2025-04-20T22:21:37.668+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-20T22:21:37.682+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T22:21:37.684+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
